apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-dep
  namespace: devops
  labels:
    app:  nginx-dep
spec:
  selector:
    matchLabels:
      app: nginx-dep
  replicas: 3
  template:
    metadata:
      labels:
        app:  nginx-dep
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx-dep
        image:  nginx:alpine
        resources:
        ports:
        - containerPort:  80
          name:  nginx-dep
      restartPolicy: Always
