apiVersion: v1
kind: Pod
metadata:
  name: quota-test-pod
  namespace: prod-namespace
spec:
  containers:
  - name: test-container
    image: nginx
    resources:
      requests:
        cpu: "1"
        memory: "512Mi"
