apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: prod-namespace
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "15"
    limits.memory: "30Gi"
