apiVersion: v1
kind: Pod
metadata:
  name: test-pod-exceed
  namespace: dev-namespace
spec:
  containers:
  - name: test-container
    image: nginx
    resources:
      requests:
        cpu: "3"        # Exceeds the max limit of 2 CPU
        memory: "2Gi"   # Exceeds the max limit of 1Gi memory
